### ISSUE TITLE
Generated page's "update_time" is related to local time

### ISSUE THREAD

**Issue by cydu** [kuangyh/kuangyh.github.io#1]
https://github.com/kuangyh/kuangyh.github.io/blob/master/generate-site.py#L21

Generated page's "update_time" is related to local time. Try to use git log find the real update time of the article? 

And I've found some small typo, should I create an issue or Pull Requests?

**Comment by kuangyh** [comment]
The general workflow is first generate-site then git commit, so look into github log would not work.

Feel free to send pull requests but I would probability just ignore it :-)

**Comment by cydu** [comment]
OK, I got it. ^_^
